# Generated by Django 6.1 on 2026-08-31 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                (
                    "dedupe_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                ("scope", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "causation_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("suppressed_reason", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "event record",
                "verbose_name_plural": "event records",
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_key", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                            ("orphaned", "Orphaned"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("available_at", models.DateTimeField(db_index=True)),
                ("claimed_by", models.CharField(blank=True, max_length=255)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="django_domain_events.eventrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery record",
                "verbose_name_plural": "delivery records",
            },
        ),
        migrations.AddIndex(
            model_name="eventrecord",
            index=models.Index(fields=["name", "recorded_at"], name="django_doma_name_90e2a3_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["available_at"],
                name="dde_pending_by_available_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrecord",
            constraint=models.UniqueConstraint(
                fields=("event", "receiver_key"),
                name="unique_delivery_per_event_and_receiver",
            ),
        ),
    ]
