# Generated by Django 6.1 on 2026-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_domain_events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deliveryrecord",
            name="dde_pending_by_available_at",
        ),
        migrations.AlterField(
            model_name="deliveryrecord",
            name="available_at",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                condition=models.Q(("status__in", ["pending", "failed"])),
                fields=["available_at"],
                name="dde_owed_by_available_at",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                condition=models.Q(("status", "claimed")),
                fields=["lease_expires_at"],
                name="dde_claimed_by_lease",
            ),
        ),
    ]
