# Generated by Django 5.2.17 on 2026-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_domain_events",
            "0002_remove_deliveryrecord_dde_pending_by_available_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrecord",
            name="succeeded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
