# Generated by Django 6.1 on 2026-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_domain_events", "0004_backfill_succeeded_at"),
    ]

    # Every existing row is a delivery to a receiver without targets=, so it
    # gets the blank target and the digest of the blank target: the literal
    # below is sha256(b"").hexdigest(), written out rather than computed so the
    # migration cannot change if the helper ever does. The model field keeps no
    # default (preserve_default=False), because a default there would let a
    # later write store it beside some other target.
    #
    # The new constraint is added before the old one is removed, so a backend
    # without transactional DDL never has a moment where the table accepts two
    # rows for one delivery.
    operations = [
        migrations.AddField(
            model_name="deliveryrecord",
            name="target",
            field=models.TextField(blank=True, default=""),
        ),
        # A plain string field, not TargetDigestField: that class now stores raw
        # bytes, and a migration naming it would build a binary column here and
        # hand 0006 a value it cannot convert. This is the column as it was
        # created - 64 characters, not editable - which is all the state this
        # migration ever described. No database that already applied it sees a
        # difference.
        migrations.AddField(
            model_name="deliveryrecord",
            name="target_digest",
            field=models.CharField(
                default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                editable=False,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="deliveryrecord",
            constraint=models.UniqueConstraint(
                fields=("event", "receiver_key", "target_digest"),
                name="unique_delivery_per_event_receiver_and_target",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="deliveryrecord",
            name="unique_delivery_per_event_and_receiver",
        ),
    ]
