# Generated by Django 6.1 on 2026-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_domain_events", "0004_backfill_succeeded_at"),
    ]

    # The new constraint is added before the old one is removed, so a backend
    # without transactional DDL never has a moment where the table accepts two
    # rows for one delivery. Every existing row gets the blank target, which is
    # what a receiver without targets= writes, so the old rows already satisfy
    # the new constraint and no backfill is needed.
    operations = [
        migrations.AddField(
            model_name="deliveryrecord",
            name="target",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="deliveryrecord",
            constraint=models.UniqueConstraint(
                fields=("event", "receiver_key", "target"),
                name="unique_delivery_per_event_receiver_and_target",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="deliveryrecord",
            name="unique_delivery_per_event_and_receiver",
        ),
    ]
