# Generated by Django 6.1.1 on 2026-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_domain_events", "0006_due_at_retention_and_binary_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiverLastSuccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_key", models.CharField(max_length=255, unique=True)),
                ("last_succeeded_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "receiver last success",
                "verbose_name_plural": "receiver last successes",
            },
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                condition=models.Q(("status", "succeeded"), _negated=True),
                fields=["event"],
                name="dde_unfinished_by_event",
            ),
        ),
    ]
