# Generated by Django 6.1 on 2026-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner", models.CharField(max_length=64)),
                ("event_name", models.CharField(max_length=255)),
                ("event_id", models.BigIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner", models.CharField(max_length=64)),
                ("event_name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "event_name"), name="one_subscription_each"
                    )
                ],
            },
        ),
    ]
